// <auto-generated />
namespace BITCollege_DP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class A4_model_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(A4_model_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "202402182039173_A4_model_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
